// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrate necesita la conexión DIRECTA (5432), no la del pooler (6543):
    // el pooler de Supabase no soporta el modo de transacción que usan las migraciones.
    url: process.env["DIRECT_URL"],
  },
});
